<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <CodeAnalysisRuleSet>..\Analyzers.ruleset</CodeAnalysisRuleSet>
    <RootNamespace>Template</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="3.3.0" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.103.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
    <PackageReference Include="Usa.Smart.Core" Version="2.16.0" />
  </ItemGroup>

</Project>
